### ISSUE TITLE
ConcurrentModificationException with Rats installed alongside

### ISSUE THREAD

**Issue by TheCoolestPaul** [Glitchfiend/SereneSeasons#304] opened 2021-01-31 00:10 UTC
### What's the issue you encountered?

The server crashes after a few minutes with players in the server.

### How can the issue be reproduced?

Run a server with both the [Rats mod](https://www.curseforge.com/minecraft/mc-mods/rats) and SS,
after a few minutes with players the server will crash.

### Logs
[crash-2021-01-30_17.58.13-server.txt](https://github.com/Glitchfiend/SereneSeasons/files/5898986/crash-2021-01-30_17.58.13-server.txt)
[debug.log](https://github.com/Glitchfiend/SereneSeasons/files/5898987/debug.log)
[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/5898988/latest.log)

### Mod Version
1.16.5-4.0.1.89

**Comment by Forstride** [comment] 2021-01-31 01:22
You have a *lot* more than just SS and Rats installed...Unless you've tested it in a separate instance with *just* those, I'm not sure how you can be certain the issue is related to SS.

**Comment by Adubbz** [comment] 2021-01-31 01:58
There’s also nothing in that log to indicate this is an issue with SS either.

**Comment by TheCoolestPaul** [comment] 2021-01-31 02:36
After removing SS as a test, there is no longer a crash.

**Comment by Adubbz** [comment] 2021-12-27 23:05
Closing this as there's nothing to indicate this is an issue on Serene Seasons' side.

**Closed by Adubbz** 2021-12-27 23:05 UTC
Labels: bug-minor
