### ISSUE TITLE
[1.20.1 newest version] Crash whilst exception in server tick loop

### ISSUE THREAD

**Issue by vinnyg0621** [Glitchfiend/SereneSeasons#499] opened 2024-10-10 21:48 UTC
### What's the issue you encountered?

when I reloaded my resource packs my server closed and took me back to the multiplayer menu even when I was on singleplayer, and then I re-opened my world and crashed with exit code -1 and saying "java.lang.NoSuchFieldError: generateSnowAndIce"

### How can the issue be reproduced?

1. go into a singleplayer world
2. reload resource packs
3. the server will say "connection lost - server closed" and take you back to multiplayer menu
4. click singleplayer menu
5. go onto the last world

### Logs

https://mclo.gs/shgdR0k

### Mod Version

9.1.0.0

### Additional information

other mods with this mod:

- snow! real magic
- serene seasons fix
- better days
- glitch core

crash report: https://gist.github.com/vinnyg0621/5851f6e02e0256641c5521d49c244336

_why is it a client crash????!_

**Comment by Forstride** [comment] 2024-10-10 22:24
Duplicate of #498

(For further reference, this is due to mods that have compatibility for Serene Seasons needing to update for the new backport.  I'd suggest downgrading the mod for the time being)

**Closed as completed by Forstride** 2024-10-10 22:24 UTC

**Comment by vinnyg0621** [comment] 2024-10-21 02:19
issue still persists.

**Comment by vinnyg0621** [comment] 2024-10-21 02:25
> issue still persists.

nvm, i updated "snow under trees"
