### ISSUE TITLE
[Crash] Mixin transformation of net.minecraft.class_761 failed

### ISSUE THREAD

**Issue by vico93** [Glitchfiend/SereneSeasons#458] opened 2024-02-18 14:23 UTC
### What's the issue you encountered?

Basically i'm having this issue since 9.3.0.19.

Trying to add SS to my modpack causes this crash. Strangely, GlitchCore and BoP didn't cause such issues.

### How can the issue be reproduced?

1. Add SereneSeasons to the modpack;
2. Try to run the game;
3. Crashes.

### Logs

https://gist.github.com/vico93/ec7f538af7f4d5a2e00374375d6df526

### Mod Version

9.3.0.20

**Comment by Adubbz** [comment] 2024-02-19 00:39
This is an issue with MoreCulling. (Duplicate of #452)

**Closed as completed by Adubbz** 2024-02-19 00:39 UTC
