### ISSUE TITLE
1.16.4 server crash generating world

### ISSUE THREAD

**Issue by Terpo** [Glitchfiend/SereneSeasons#279] opened 2020-12-26 18:57 UTC
## Bug Report
server crash generating world

### What's the issue you encountered?
server crashed while generating chunks and biomes

### Logs
https://gist.github.com/Terpo/51823238ea268fc1fcdd4c7c0cfcaf8d
I also dumped the biome registry but it seems rats:ratlantis_biome does not even show up properly, so it might be a problem on rats end. Another issue was, that the biomes was generated in the overworld at all.

### Mod Version
1.16.4
forge-1.16.4-35.1.11
SereneSeasons-1.16.4-4.0.0.81-universal
TerraForged-1.16.4-0.2.0-ALPHA-4
ratlantis-1.0.0-1.16.3
rats-7.0.1-1.16.3

-- quickfix --
prevent generating rats:ratlantis_biome in overworld by blacklisting the biome in 
config\terraforged\biome_weights.conf by adding "rats:ratlantis_biome" = 0

**Comment by Adubbz** [comment] 2020-12-26 21:52
This has already been fixed. You need to update the mod.

**Comment by Adubbz** [comment] 2020-12-26 22:32
My bad. I initially closed this because I saw the version was reported as ``1.16.4-4.0.0.76``, but it seems that's a different issue with our build system not updating it correctly.

I would still say this is not an issue with Serene Seasons though. This is indeed caused by biomes being absent from the registries when they shouldn't be.

**Comment by Adubbz** [comment] 2020-12-26 23:05
I've attempted to add a potential workaround for this, however it's working on the assumption that it's a registry synchronization issue (since I have no idea what rats is doing). If that isn't the case and they are in fact not registering their biomes at all, then I would deem this a bug on their end.

**Comment by Terpo** [comment] 2020-12-26 23:49
I reported it to rats too so they can take a look into it too.

**Comment by Adubbz** [comment] 2020-12-27 00:00
Have you tried a build with the changes I just made?

**Comment by Terpo** [comment] 2020-12-27 10:29
Just tried it with your fixed version and it works. But still, .... ratlantis is not meant to be generated in the overworld so I deactivate it again.
![grafik](https://user-images.githubusercontent.com/4256058/103168807-c1b17b00-4836-11eb-8894-efbfd207a98c.png)

**Comment by Forstride** [comment] 2020-12-27 10:54
Try it *without* Terraforged.  People have been reporting biomes from other dimensions generating in the overworld with Terraforged installed, and we need to know if it's actually them or us.

**Comment by Forstride** [comment] 2020-12-27 11:18
Oh wait, I had a brainfart and thought this issue was open on the BOP repo.  Yeah, that's DEFINITELY a TerraForged issue then.  Serene Seasons does not change world gen at all

**Closed by Forstride** 2020-12-27 11:18 UTC
Labels: bug-minor

**Comment by Won-Ton** [comment] 2020-12-28 18:01
Nah that's not TerraForged's doing. If you make chunk errors by chopping and changing biome mods or doing weird things with your world data then the errors would be chunk-aligned under TerrForged's chunk generator. The worldgen in that screenshot looks to be vanilla to me - TF's alpha version doesn't let you disable custom trees yet and those are all vanilla's.

The originally reported crash isn't related to TF either. Taking a peek at ratlantis's jar it appears that their biomes are purely datapack driven so they wouldn't appear in the forge registry. SereneSeasons should probably be quering the DynamicRegistries to avoid this crash - I'd expect SS to crash like this with any datapack-added biomes installed.
