### ISSUE TITLE
Internal Exception java.lang.IndexOutOfBoundsException on Direct Connect session

### ISSUE THREAD

**Issue by Truthseer27** [Glitchfiend/SereneSeasons#388] opened 2022-08-18 12:50 UTC
### What's the issue you encountered?

When client joins a Direct Connect session with a LAN server, the joining client will invariably lose connection with the following error:

`Connection Lost - Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(4) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 2, widx: 4, cap: 4)`

The server-side game will remain running and without interruption.

### How can the issue be reproduced?

This issue occurs with any Serene Seasons 1.19 mods on any Forge 1.19 version later than 41.0.63 (this includes any Forge versions for 1.19, 1.19.1, 1.19.2). My latest attempt was made with SereneSeasons-1.19-8.0.0.20 on 1.19.2-forge-43.1.1. Using some versions of Forge will only return the "IndexOutOfBoundsException" with no other details (no byte buffer error is shown). For example, Forge 1.19-41.1.0 does this.

NOTE: I have not actually tested any Forge 1.19 versions between 41.0.64 and the highest 41.0.xxx version. Forge 1.19 41.0.64 "broke" a lot of my mods and it took until 41.1.0 for me to get the majority of the "broken" ones working again. I do know that SereneSeasons-1.19-8.0.0.17 worked with 41.0.63 (see "Additional Information" below) and I believe SereneSeasons-1.19.8.0.0.18 was compatible with 41.0.64 up to the highest 41.0.xxx version. Forge 1.19 41.1.0 and higher requires at least SereneSeasons-1.19-8.0.0.19.

Both the server and the client were running `preview_OptiFine_1.19.1_HD_U_H9_pre1` mod and `SEUS-Renewed-v1.0.1` shader pack, but no other mods, resource packs, datapacks, etc.

A YggdrasilMinecraftSessionService error and a couple of Netty Client IO errors occur in the latest.log file:
` [Worker-Main-12/ERROR] [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService/]: Signature is missing from textures payload`
`[Netty Client IO #0/ERROR] [net.minecraftforge.network.simple.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel sereneseasons:main_channel`
`[Netty Client IO #0/ERROR] [net.minecraftforge.network.simple.IndexedMessageCodec/SIMPLENET]: Received invalid discriminator byte 109 on channel sereneseasons:main_channel`

### Logs

https://gist.github.com/Truthseer27/6aa5d8340b4b988e0daded1ba58f4377

### Mod Version

1.19-8.0.0.20

### Additional information

For comparison (and in contrast) to my reported issue, I can connect successfully and without interruption when using SereneSeasons-1.19-8.0.0.17 on 1.19.forge-41.0.63. Both the server and the client were running `preview_OptiFine_1.19_HD_U_H9_pre2` mod and `SEUS-Renewed-v1.0.1` shader pack, along with 56 other mods.

**Comment by kralrindo** [comment] 2022-08-18 13:36
I also have same issue

**Comment by NotLazy** [comment] 2022-09-07 20:58
+1 I also have this issue.

**Comment by M4theusRibeiro** [comment] 2022-09-11 01:42
i also have this issue

**Comment by Pereirarthur** [comment] 2022-09-20 01:20
This also happened to me

**Comment by Adubbz** [comment] 2022-09-21 03:03
I can't reproduce this with Serene Seasons on its own so I'm inclined to think it's an issue with Optifine

**Comment by NotLazy** [comment] 2022-09-21 03:39
> I can't reproduce this with Serene Seasons on its own so I'm inclined to think it's an issue with Optifine

I experience this issue using ONLY forge and serene seasons. No optifine.

**Comment by kolyambo** [comment] 2022-10-13 14:16
Same issue. Only forge (43.1.1) and Serene seasons ( SereneSeasons-1.19.2-8.1.0.21.jar ), no other mods and no optifine. I'm playing with CurseForge app.

**Comment by ghost** [comment] 2022-10-26 06:52
Yep same issue for me too. Seems to only be a 1.19 problem since this didn't happen in 1.18.2

**Comment by taunnol** [comment] 2022-10-26 09:46
Encountered same issue. 1.19.2, Forge 43.1.43. In some cases instead of mentioned error the game starts to lag a lot (with subsequent disconnect from the host)

**Comment by justfigure** [comment] 2022-11-21 21:18
dev grab werench and fix problem with their codey or forge dev grab eniggener gaming and fix problemo

**Comment by Adubbz** [comment] 2022-12-11 01:05
I'm gonna close this, since this does not seem to be occurring anymore. Proof:
![image](https://user-images.githubusercontent.com/2765389/206881580-a388e82b-7178-40ab-8d29-bd60d30da93d.png)

**Closed as completed by Adubbz** 2022-12-11 01:05 UTC

**Comment by gquester** [comment] 2023-03-23 23:37
I resolved this issue by disabling Serene Seasons in the Modded OneBlock modpack that I was playing.  I guess in this case you are out Serene Seasons, but at least you do not get the Connection Lost error.  Also, you have to disable Serene Seasons on each PC that is running MineCraft.

**Comment by EternalSoul15** [comment] 2024-04-14 21:35
i dont have serene seasons and this error is happening
