### ISSUE TITLE
LAN server issues connecting

### ISSUE THREAD

**Issue by HentaiHamster** [Glitchfiend/SereneSeasons#353] opened 2021-10-04 14:52 UTC
So I open my SP world to Lan for my friend to join but he can't when this mod is enabled. It is definitely this mod because I got rid of it and he can join fine we play multiple time then I try to re-enable and it doesn't work. I am using the latest version of the mod for 1.17.1  ...1.17.1-5.0.0.6. It doesn't give an error message when he joins it just says encrypting then when he joins he immediately disconnects. I have tested this multiple times and it is definitely this mod. I guess the only thing I haven't tried is to use the beta versions or just a different version of the mod and see if the problem persists. I will try that later today and update my post.  In the meantime any ideas on a way to fix this problem or why it is occurring? Thank you for any info or help!!

**Comment by baronvertigovongrahamthesecondofsealand** [comment] 2021-11-03 05:50
I also have this issue with the "Open to LAN" function. Biomes'o'plenty works fine, Serene Seasons drops the player as soon as they enter, sometimes giving the error:

`io.netty.handler.codec.encoderexception io.netty.util.illegalreferencecountexception refcnt 0`

**Comment by RiverC** [comment] 2021-11-23 20:10
Can third this. I believe that this is a compatibility issue with Netty (which MC uses to connect and was recently updated) and refcnt 0 has to do with how packets are now being handled, differently now, that causes some mods to fail in 1.17 multiplayer. 

This kicks the player out because their network connection immediately hits a fatal error handling packets.

**Comment by isuke01** [comment] 2022-01-10 20:37
Same issue at 
Minecraft 1.18.1 
Forge 39.017
SereneSeasons-1.18.1-6.0.0.8
Error same as @baronvertigovongrahamthesecondofsealand  said.
We tested it with the only this mod activated.

**Comment by isuke01** [comment] 2022-01-12 23:13
IS there any temp fix for it or something ?

**Comment by RiverC** [comment] 2022-01-14 18:46
The only temp fix is to run a dedicated server on your PC rather than running a LAN game, as the dedicated server doesn't use Netty

**Comment by Adubbz** [comment] 2022-12-11 01:06
Duplicate of #388

**Closed as completed by Adubbz** 2022-12-11 01:06 UTC
