### ISSUE TITLE
Seasons changing randomly every time I sleep in bed

### ISSUE THREAD

**Issue by ThePieGuyWill** [Glitchfiend/SereneSeasons#221] opened 2020-01-07 10:16 UTC
For some reason, the seasons change randomly every time I got to sleep, 

What's the issue you encountered?

For some reason, the seasons change randomly every time I got to sleep, the seasson work find if I dont go to sleep

How can the issue be reproduced?

Do the /time set midnight and then use a beg to sleep the night, when your wake up you should see the season would have changed some something completely different

Mod Version

SereneSeasons-1.15.1-3.0.0.39-universal

**Comment by ThePieGuyWill** [comment] 2020-01-07 10:25
NOTE: I am using a world that was generated without the mod, I only installed the mod yesterday

**Comment by resinate** [comment] 2020-01-08 20:58
same here, it was late autumn then switched to early summer lol

**Comment by ThePieGuyWill** [comment] 2020-01-08 23:26
It's really anoying, especially when growing plants due to their fertile seasons always changing

**Comment by MattEDG125** [comment] 2020-02-09 18:43
Had the same problem but when I removed MixinBootstrap-1.0.1.jar it got fixed.

**Comment by ThePieGuyWill** [comment] 2020-02-10 08:25
Where's that file located?

**Comment by Forstride** [comment] 2020-02-10 09:59
MixinBootstrap is not a file included with Serene Seasons, and seems to be a dependency for other mods.  I can't reproduce this issue at all, so it's likely another mod interfering like @MattEDG125 suggested.

**Comment by Forstride** [comment] 2020-02-21 08:59
Closing this because no additional follow up was made, and I'm assuming it was resolved

**Closed by Forstride** 2020-02-21 08:59 UTC
