### ISSUE TITLE
Snow doesn't accumulate with snowAccumulationHeight turned up.

### ISSUE THREAD

**Issue by LazrProductions** [Glitchfiend/SereneSeasons#417] opened 2023-06-17 02:03 UTC
### What's the issue you encountered?

In 1.20, While snowing in biomes that don't normally snow, and with the gamerule snowAccumulationHeight turned above 1, snow doesn't accumulated.

### How can the issue be reproduced?

Create a world, set snowAccumulationHeight to 2-8, then set the season to winter and the weather to rain.

### Mod Version

1.20-9.0.0.41

**Comment by Adubbz** [comment] 2024-01-16 01:50
Duplicate of #397

**Closed as completed by Adubbz** 2024-01-16 01:50 UTC
