### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by szunakabeats** [Glitchfiend/SereneSeasons#454] opened 2024-02-07 08:39 UTC
### What's the issue you encountered?

Minecraft is not starting.

[crash-2024-02-07_09.32.32-client.txt](https://github.com/Glitchfiend/SereneSeasons/files/14191010/crash-2024-02-07_09.32.32-client.txt)

[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/14191037/latest.log)

### How can the issue be reproduced?

dont know exactly because i added them to my small modpack with 50 mods. mostly performance mods.

### Logs

https://gist.github.com/szunakabeats/0f078d4e8ab3807d89ff49698e78e945

### Mod Version

1.20.4-9.3.0.18

**Comment by Adubbz** [comment] 2024-02-07 09:13
Duplicate of #452

**Closed as completed by Adubbz** 2024-02-07 09:13 UTC
